### ISSUE TITLE
show result in moves list

### ISSUE THREAD

**Issue by michmeucci** [mliebelt/PgnViewerJS#114]
the result 0-1 or 1-0 doesn't appear in the move list how can let the script display it?

**Comment by mliebelt** [comment]
I checked it, and there is no such option (yet). So if you want to include the result of the game not only in the header (where it is displayed), but in the moves list, I have to add an option as part of the many parameters. How about `showResult` (with default false, so that there is no change if you don't use that option), and when this option is set to true, it will be shown at the end of the list. I will use the definition from the specification, see [PGN Specification](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm#c8.1.1). Is that ok?
