### ISSUE TITLE
Allow the  display of many games at one place

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#12]
PGN as a format allows to have more than one game. So it should be easy to provide a UI that allows to play through many games at the same place.

The following should be done to do that:
- Allow to parse many games at once. This could be done by enhancing the grammar, or by a pre-processing that splits the included games into many before using the parser.
- Add a drop-down box for selecting the game that should be shown. The display in the drop-down should include relevant information like players, round, ... which may depend on the kind of games that are played here.
- Add a configuration parameter, to make explicit that many games should be read at once.

**Comment by calvicius** [comment]
firstly... my english si not very good....

welll...
I have a problem with fen positions
Your edit.html example 
originaly inits with position:'start'. So ... if I change the start position with a fen with side to move as black; lets say : position : 'rnbqkbnr/pp1p1ppp/4p3/4P3/2PQ4/2N5/PP3PPP/R1B1KBNR b KQkq - 0 6' always inittiates the process as white to move.

I have also tried to change in html like this : 
    quote\<script id="identificador_js" cadena="<?echo $cadena1; ?>" src="../js/pgnvjs.js" type="text/javascript"></script>\unquote

and then change pgnvjs like this
//recuperamos la query string
var locojo=document.getElementById('identificador_js');
var esmio=locojo.getAttribute('cadena');

for receiving the fen chain, then I have changed this (ten lines below):
	//var game = new Chess();
to
	var game = new Chess(esmio); with "'"+esmio+"'" also

and the problem persists.

it would be very appreciated in my side if there is any solution that I have ommited.
thanks in advance,
calvicius

**Comment by mliebelt** [comment]
@calvicius  Did you manage to solve the problems you faced? I would like to help you somehow, but to do that, I would like to take your comment as a separate ticket.

So perhaps I need the minimal example to show how to use PgnViewerJS in the most efficient way. Is that needed any more?

**Comment by calvicius** [comment]
thanks for your interest.
yes, it was solved.
in the meantime y have done one editor/viewer for multiples pgns (dependant of ram memory) only for entertainment.

If you (and everybody) is interested it can be downloaded from:

https://drive.google.com/file/d/0Bz_5GBxD4LKIWm9xTzl0X01DS1U/view?usp=sharing

the internal schema is and array of arrays, in order to emulate a tree of n-nodes; and codification is not very elegant, but the idea may serve to others. Note: is in spanish

**Comment by cxd4** [comment]
@mliebelt Please do find some time to have this feature working.

Among other web-friendly PGN viewers I've tested so far, yours is the most thorough and well-developed, but its fatal flaw for my means comes down to just this one and only feature's absence.

Currently I am stuck depending on a restrictively licensed, unmodifiable PGN viewer by Chess Tempo.  It supports the multiple-games-per-PGN feature you mentioned in my own personal database I have stored here:  https://cxd4.github.io/uscf/play.html?f=2018/08100812.pgn

In this case I use JavaScript to read from the `...f="filename.pgn"` suffix to the URL as which of my PGN databases of my games I want to review, and inside each PGN is a tournament's worth of games.  I was hoping I could finally get rid of Chess Tempo's PGN viewer but was disappointed at the road block I hit while migrating to yours, because only the first and foremost round of each tournament is viewable in my page.  I can't picture splitting all my tournament databases into single games per multiple PGN files.

>Add a configuration parameter, to make explicit that many games should be read at once.

A configuration parameter is probably safest as a start point, because with said parameter turned off or set to false, the current PGN parsing procedures in your scripts can remain traditional without being distracted by searching for more than one game inside a PGN.  In the long run, though, detecting the presence of multiple games instead of relying on an explicit config parameter would probably be simpler, as too many config options (including a questionably useful option to only show the top-most game inside a potentially massive PGN file) can complicate things as well.

**Comment by gbtami** [comment]
@cxd4 have you tried http://pgn4web.casaschi.net ?
https://sourceforge.net/p/pgn4web/code/HEAD/tree/trunk/

**Comment by cxd4** [comment]
@gbtami I avoided pgn4web initially due to the project saying it was written partially in PHP, and, just in case that meant what I feared, I wanted to avoid wasting time trying to install PGN viewers that required server-side scripting like PHP.  I tried PgnViewerJS first because it's a 100% JavaScript-focused project.

However, I am successful so far with getting pgn4web to work with my offline website.  It appears to do just what I need.  I will be using pgn4web at least until PgnViewerJS supports actual PGN file databases.  Thanks.

**Comment by mliebelt** [comment]
For me, the feature has not a high priority, due to the fact, that I use the viewer mostly in our web site of our local chess club, to display games alone. 

The description of the feature is sufficient, for any one interested to implement the feature on their own. Anyone?

I have done a lot of things lately not related to the PgnViewerJS, therefore I cannot promise to implement something like that soon ...

**Comment by cxd4** [comment]
I understand.  I'm a little primitive with my application of JavaScript and experience with it, but I'll try to find some time to investigate how to implement it myself.

For examples, I have used 2 PGN viewers besides this one which demonstrate effectively working import of multi-game PGN databases.

1.  [Chess Tempo](https://chesstempo.com/pgn-viewer.html)
2.  [pgn4web](http://pgn4web.casaschi.net/collection.html?pgnFile=chess-informant-sample.pgn&title=Chess)

Both of those show a drop-down box that lets you pick which game to view.  (I'll never go back to Chess Tempo's though because that's licensed under non-free and restrictive licensing.)

>For me, the feature has not a high priority, due to the fact, that I use the viewer mostly in our web site of our local chess club, to display games alone.

I guess for something like that, there isn't much of a game "Round" concept (as in the Round field required by the seven-tag PGN roster).  One game per PGN file could work in theory in the non-tournament or casual event cases, but even in a chess club I'd probably feel like grouping all the games I play within a certain period or so, depending on the circumstances.  Maybe not.

**Comment by mliebelt** [comment]
I finally created a working solution. See the example file [many-games-left.html](https://github.com/mliebelt/PgnViewerJS/blob/master/modules/pgn-viewer/examples/modes/view/many-games-left.html) how to do it.
