### ISSUE TITLE
Piece positioning at top left

### ISSUE THREAD

**Issue by awormuth** [mliebelt/PgnViewerJS#123]
Hello,

We have noticed an odd behavior where the pieces sometimes display at the top left corner. We don't see any javascript errors, and it seems to only sometimes happen on the first page load (so maybe a dependency issue, or cache issue, or load speed issue).

For more context, the chess tool we are building is rendered inside of an iFrame. 

Do you have any thoughts as to what might cause something like this to happen?
<img width="111" alt="Screen Shot 2019-10-20 at 8 11 21 AM" src="https://user-images.githubusercontent.com/2530972/67161755-84885980-f312-11e9-8e8a-2d94648c082e.png">

**Comment by mliebelt** [comment]
I don't have any idea. As you may have noticed, I am just using https://github.com/ornicar/chessground so I do not know how to debug such a behavior. I never saw that in my usage of PgnViewerJS, so no idea what is happening here.

**Comment by mliebelt** [comment]
Please have a look at #145, which exactly described when it happened. There a call to redrawAll of Chessground was sufficient to fix the problem. It seems to be a race condition where the board is not in HTML rendered, so no context (width, height) is known. 

Please have a look at the solution there, perhaps that eventHandler to redraw it will fix it as well for you. I will close that bug, because I am not able to reproduce it.
