### ISSUE TITLE
Usage with react?

### ISSUE THREAD

**Issue by victorocna** [mliebelt/PgnViewerJS#162]
Hello! Great stuff in this repo, I've been checking it out from time to time.

Not an actual issue, more like a question: 
Any ideas on how it can be used in a React project?

**Comment by mliebelt** [comment]
No idea at all. I have (nearly) no experience with React, but it should be solvable. You have to ensure that the resources (locales and images) are found. Locales are normally found nearby the library, the structure normally is:

    root/
      js/      // Just as example
        pgnv.js
        locales/
           buttons-en.json
            ...

The images are nowadays pre-packaged by webpack, and are expected to be in `/pgnv-assets`. I don't know what happens if you pack your react application (again), if the assets are treated well.

I have done some research, see my [example for webpack](https://github.com/mliebelt/example-webpack-dynamic-resources) how resources may be found variably. Ï have used that myself, when deploying the examples to Github pages. The examples in https://mliebelt.github.io/PgnViewerJS/examples.html#1000 work only, because the path to the assets was patched. The  relevant part to the HTML page is:

    <script>__globalCustomDomain = '/PgnViewerJS/js/';</script>
    <script src="./js/pgnv.js" type="text/javascript"></script>

So the path to the assets can be defined before the library is loaded.

**Comment by victorocna** [comment]
Sure, it makes sense to pre-package images with webpack. In my project, however, I'm already using chessground, so resources should be already available and bundled by webpack.

I've created a minimal implementation of chessground in React:
https://github.com/victorocna/react-chessground-starter

Assuming that I don't need locales and the project already has the resources needed to render the board, how can I start implementing the viewer? Is there a version of the viewer that can work side-by-side with chessground?

Cheers!

**Comment by mliebelt** [comment]
I don't understand your question. The viewer does a lot of stuff, and it is the way it is. If you want to implement your own version, feel free to clone and change it. But why should I remove features that are working. So having the viewer internationalised is essential for me, so the locales are needed. If you leave them out, all will be English only (the default). The images I have added are mostly additional piece types and background images for squares. If you don need them, just go without them. So you could just take the library ( `pgnv.js`) and use it directly.

**Comment by victorocna** [comment]
> So you could just take the library ( pgnv.js) and use it directly.

Thanks for your suggestion. I'll try to do just that :)

**Comment by mliebelt** [comment]
I have bundled in the meanwhile the pieces together with the javascript code. By modifying the webpack files, you  should be able to create your own version. I have set the piece style, and the CSS references this. I do not know what will happen then.

**Comment by mliebelt** [comment]
There is even that issue #196 where one can see how to use PgnViewerJS inside react. I think I will close that ticket, because there will be no "solution" in the short run.
