### ISSUE TITLE
NAGS: A few suggestions

### ISSUE THREAD

**Issue by braoult** [mliebelt/PgnViewerJS#250]
Currently, with the moves `1. e4 $1 $10 $13 e5 $44`, the HTML becomes (I added newlines for readability): 
```
<span id="boardMoves0" class="move white">
  <a style="">e4!=∞</a>
</span>
<span id="boardMoves1" class="move">
  <a style="">e5=∞</a>
</span>
```
And displayed as   **1. e4!=∞ e5=∞**. 

There are many issues :
1) For obscure NAGs, the user will have no idea of what it can mean.
  One solution could be to separate the nags in separate elements, and offer a tooltip
2) Even if this example is not good, and may look stupid (like "equal" and "unclear" together), this is what the annotator wanted to write, and two different annotations ($10+$13) & ($44) become the same, but they are not.

My suggestion would be to have HTML designed as following :
```
<span id="boardMoves0" class="move white goodMove">
  <a style="">e4<span class="nag move">!</nag></a>
  <span class="nag position">=</span>
  <span class="nag position">∞</span>
</span>
<span id="boardMoves1" class="move">
  <a style="">e5</a>
  <span class="nag position">=∞</span>
</span>
```
And I think the display should be: **1. e4! = ∞ e5 =∞**. 
Doing this will give many advantages:
1) Associating a class for the move appreciation (`goodMove` in the example), that are NAGs 1-9, we could display them differently (Lichess does that for example), this is useful to see where a game changes orientation.
2) Visually separating non move-related NAGs allows easier reading
3) Giving classes to NAGs allows many things, such as decoration (colors), tooltips, etc...

What do you think about it ?

**Comment by mliebelt** [comment]
To be fair: way too much! Have you read the [PGN Specification](https://github.com/mliebelt/pgn-spec-commented/blob/main/pgn-specification.md#10-numeric-annotation-glyphs)? You should do it, to see, that there is not too much specified. And sorry, but I am not "your worker". So please, stop creating many, many tickets, because I am not able to keep that pace. 

I don't say, that those ideas are bad, but I cannot change everything on a daily base (for you only). Btw, ever thought why people are working for nothing? Have a look at stars, nice comments, thank you here and there. Sorry, but I miss that in your many posts. 

Could you please start a discussion about this, so perhaps it is a good idea, perhaps it is not needed at all. And please, allow me to have some time that I am able to spend on whatever I want to do.

**Comment by braoult** [comment]
Moving to Discussions
