### ISSUE TITLE
Incomplete git clone instructions

### ISSUE THREAD

**Issue by lorenzo-leuck** [mliebelt/PgnViewerJS#396]
In order to get the lib folder you need to run npm install and run build in the "pgn-reader" module. Please add these steps in the read.me. Also, great work! Greetings from brazzzil

**Comment by mliebelt** [comment]
Thanks for draw that to my attention. Yes, the problem stems from having 2 modules, and you have to use the published module, if you want to build only the pgn-viewer. I will do some tests, but this should only be necessary if a temporary version of the pgn-reader should be used. Normally, it should be all the time versioned and published, so that it can be used directly in `package.json`.

I checked the current version on `main` branch, and there I have a reference to the `pgn-reader`. Can you tell me what happens when you are not doing your steps from above? A complete list of the steps you do would be helpful.

When wanting to build the `pgn-viewer`, running `npm install`, then `npm run build` should give you at the end the one file produced in the folder `lib`.

**Comment by mliebelt** [comment]
@lorenzo-leuck Any additional information? I have not received anything, and will close the opened issue then.
