### ISSUE TITLE
Provide a default configuration that may be changed programmatically

### ISSUE THREAD

**Issue by mliebelt** [mliebelt/PgnViewerJS#45]
Currently, the defaults are spread all over the source code. It would be nice to have the following:

- Centralize the defaults at one place, so it is easier to look them up.
- Allow to modify the defaults programmatically (without changing source code, of course), that will be used then instead of the defaults provided in the sources.

**Comment by xeyownt** [comment]
In PgnJS, the defaults are managed through a custom mode named `defaults` (an experimental feature for now, pending what you might do here). When using this mode, the given configuration are stored and reused for next boards. The defaults can be assigned to one or several classnames by using the attribute `class`.

I think this feature was necessary for PgnJS because, although MediaWiki supports templates and such, it is not easy to combine or complement configuration. So adding this 5th mode seems the cleanest solution.

I'm not sure though that there is such need for PgnViewerJS. In fact, in Javascript, one could easily define defaults by defining several arrays and then use a [`jQuery.extend`](http://api.jquery.com/jQuery.extend/) call to merge them.

**Comment by mliebelt** [comment]
But having default configuration programmatically allows to add it easier in other contexts (like PgnViewerJS-WP, my Wordpress plugin). There I have to repeat the configuration on each page in each game displayed. It would be nice to have:

* A central default for the whole site
* A local default, when adding multiple games on the same page

**Comment by mliebelt** [comment]
I think this is already implemented, but not documented well. There is no example using it, so I have to see how that works. Provide an example, and see how the documentation could be expanded to help understand that feature.

https://github.com/mliebelt/PgnViewerJS/blob/468c6f17fbea0856f0d015b378e7d53b588c17ab/modules/pgn-viewer/src/pgnvjs.js#L23 is the line where the normal defaults are defined.

The line https://github.com/mliebelt/PgnViewerJS/blob/468c6f17fbea0856f0d015b378e7d53b588c17ab/modules/pgn-viewer/src/pgnvjs.js#L59 merges the global configuration into the local defined one, so global set defaults will override the default ones.
